iChode/config/routes.rb
Rails.application.routes.draw do

   root 'static#home'

   match 'auth/:provider/callback', to: 'sessions#create', via: 'get'
  match 'auth/failure', to: redirect('/'), via: 'get'
  match 'signout', to: 'sessions#destroy', as: 'signout', via: 'get'

   match '/body', to: "body_parts#index", via: 'get'
   match '/exercises', to: "exercises#index", via: 'get'
   match '/motivation', to: "static#motivation", via: 'get'

   resources :body_parts do
      resources :muscles
    end

end

iChode/app/models/body_part.rb
# == Schema Information
#
# Table name: body_parts
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BodyPart < ActiveRecord::Base
	has_many :muscles, dependent: :destroy
	
end

iChode/app/models/exercise.rb
# == Schema Information
#
# Table name: exercises
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Exercise < ActiveRecord::Base
	has_many :muscle_exercises
	has_many :muscles, through: :muscle_exercises
end

iChode/app/models/muscle.rb
# == Schema Information
#
# Table name: muscles
#
#  id          :integer          not null, primary key
#  bodypart_id :integer
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Muscle < ActiveRecord::Base
	belongs_to :body_part
	has_many :muscle_exercises
	has_many :exercises, through: :muscle_exercises
end

iChode/app/models/muscle_exercise.rb
class MuscleExercise < ActiveRecord::Base
	belongs_to :muscle
	belongs_to :exercise
end

iChode/app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
  end
end
=begin
	def facebook
		@facebook ||= Koala::Facebook::API.new(oauth_token)
	end

	def friends_count
		facebook.get_connection("me", "friends").size
	rescue Koala::Facebook::APIError => e 
		logger.info e.to_s
		nil
	end
=end
end

iChode/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

iChode/app/controllers/body_parts_controller.rb
class BodyPartsController < ApplicationController
	def new
		@body_part = BodyPart.new
	end

	#dont need to worry about new since only 5 body parts set for app
	#dont worry about create
	#dont worry about destroy
	#dont worry about edit


	#list all blocks
	def index
		@body_parts = BodyPart.all
	end

	def show 
		@body_part = BodyPart.find(params[:id])
	end

	private
		def body_part_params
			params.require(:body_part).permit(:name)
		end

end

iChode/app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def new
		@exercise= Exercise.new

	end


	def index
		@exercises = Exercise.all
	end

end

iChode/app/controllers/muscle_exercises_controller.rb
class Muscle_Exercises < ApplicationController
def create
	@muscle = Muscle.find(params[:muscle_id])
	@exercise = Exercise.find(params[:exercise_id])
	@muscle_exercise = @muscle_exercise.create(muscle_params,exercise_params)
end

def show 
end

def index
end
end

iChode/app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
	def create 
		@body_part = BodyPart.find(params[:body_part_id])
		@muscle = @body_part.muscles.create(muscle_params)
		redirect_to block_path(@block)

	end

	def index
		@muscles = Muscle.all 
	end

	def show
		@muscle = Muscle.find(params[:id])
	end

	private
		def muscle_params
			params.require(:muscle).permit(:name)
		end


end

iChode/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

iChode/app/controllers/static_controller.rb
class StaticController < ApplicationController
	def home
	end

	def body
	end

	def motivation
	end
end

iChode/app/helpers/application_helper.rb
module ApplicationHelper
end

iChode/app/helpers/body_parts_helper.rb
module BodyPartsHelper
end

iChode/app/helpers/exercises_helper.rb
module ExercisesHelper
end

iChode/app/helpers/muscles_helper.rb
module MusclesHelper
end

iChode/app/helpers/sessions_helper.rb
module SessionsHelper
end

iChode/app/helpers/static_helper.rb
module StaticHelper
end

iChode/app/views/body_parts/index.html.erb
<div id="picturebox">

<div id="bodymenubox">

	<% @body_parts.each do |bp| %>
		<div id="bpblock"> <%= link_to bp.name, body_part_path(bp) %> </div>
		<br>
	<%end%>
	
	<script type="text/javascript">
		//var classarray = ["m1","m2","m3","m4","m5"];
		//$("#bodymenubox").empty();


	</script>
</div>

</div>

iChode/app/views/body_parts/show.html.erb
<div id="picturebox4">

<div id="musclemenubox">
	<h1>
	<%= @body_part.name %>
	</h1>
	<div id="muscleoptions">
	<%= render @body_part.muscles %>
	</div>

</div>

</div>

iChode/app/views/exercises/index.html.erb
<div>
	<h1>Workouts!</h1>

	<% @exercises.each do |ex| %>
	<div id="exblock">
		<%= ex.name %>
	<br>
	<% end %>

</div>

iChode/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IChode</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1618842421683775',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<div id="wrapper">
	<%= yield %>
</div>

</body>
</html>

iChode/app/views/muscles/_muscle.html.erb
<br>
<div>
	<%= muscle.name %>
</div>

iChode/app/views/muscles/index.html.erb
<div>
	<% @muscles.each do |muscle| %>
		<div id="bpblock"> <%= link_to muscle.name, muscle_path(muscle) %> </div>
		<br>
	<%end%>


</div>

iChode/app/views/muscles/show.html.erb
<div>
	<div>
		<%= @muscle.name %>
	</div>

	<div>Now show all the exercises</div>

	<% @muscle.musclesworkeds.each do |mw| %>
		Exercise id: <%= mw.exercise.id %>
	<% end %>

</div>